# Generated by Django 4.1.5 on 2023-01-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_product_image_alter_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('location', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'UserInfo',
            },
        ),
    ]
